### ISSUE TITLE
Display image output

### ISSUE THREAD

**Issue by dustinwilson00** [mokeyish/obsidian-code-emitter#13]
Is it possible for image output (such as seaborn graphs) to displayed inline?

**Comment by mokeyish** [comment]
If you are familiar with js, it can actually be done.  Assume the output is markdown, call the markdown compiler to turn it into html, and then insert it into dom.
 But I don't seem to have the energy to do this.

**Comment by drdozer** [comment]
Being able to flag the output of a cell as something that should be processed as markdown would be generally useful. For example, I could have a cell return a latex string, which is then rendered.

**Comment by mokeyish** [comment]
#16 It's supported.
