### ISSUE TITLE
Suggest for running code in editing view

### ISSUE THREAD

**Issue by h0zr** [mokeyish/obsidian-code-emitter#19]
It's a very nice plugin, but I prefer to run my python code in the editing view rather than in the reading view

Just like another plugin that runs python plugin called jupyter

**Comment by mokeyish** [comment]
I'm not sure if there is such an API.

**Comment by mokeyish** [comment]
https://github.com/mokeyish/obsidian-code-emitter/commit/3bd0c4d3a51b449f28e119227d24f7b4defd4f00
