### ISSUE TITLE
Unable to run single-line code block

### ISSUE THREAD

**Issue by FlippingBinary** [mokeyish/obsidian-code-emitter#21]
When the code block contains only a single line, the play button is overlapped by the copy button, which prevents execution of the code.

Example:

    ```typescript
    console.log("Hello, World!");
    ```

Result:

![image](https://github.com/mokeyish/obsidian-code-emitter/assets/35066367/4e9e71ce-781a-45c6-92dd-8c65424157e1)

**Comment by pchinso** [comment]
add white lines up and down, your single line...

![image](https://github.com/mokeyish/obsidian-code-emitter/assets/15819212/d96ff930-10c5-4041-bad0-c63cde6eeced)

![image](https://github.com/mokeyish/obsidian-code-emitter/assets/15819212/46c13100-ebf8-42ff-9d12-7088e080381e)

**Comment by mokeyish** [comment]
They happen to overlap, so there seems to be no solution, just add an extra blank line.
