### ISSUE TITLE
Update from 0.1.2 to 0.1.3 fails via Obsidian Community Install

### ISSUE THREAD

**Issue by ScottJWalter** [mokeyish/obsidian-code-emitter#22]
Actions:

1. Open Obsidian
2. Open Settings
3. Find Code Emitter in installed community plugins
4. Click update button

Results:
v0.1.2 remains installed

Expected Results:
v0.1.3 installed

I've also done an uninstall/delete subfolder/reinstall with the same result.

**Comment by ScottJWalter** [comment]
Looks like the manifest.json didn't get updated with the new version number.

**Comment by mokeyish** [comment]
Thanks for feedback. I've fixed it. please update again.
