### ISSUE TITLE
How to add python with pandas? 

### ISSUE THREAD

**Issue by pchinso** [mokeyish/obsidian-code-emitter#23]
Hi! 

Is possible to import Pandas in python code execution? 

![image](https://github.com/mokeyish/obsidian-code-emitter/assets/15819212/8dc50cf4-c296-4b73-a304-8ad75c396174)

**Comment by mokeyish** [comment]
https://github.com/mokeyish/obsidian-code-emitter?tab=readme-ov-file#python

**Comment by pchinso** [comment]
Thanks!

![image](https://github.com/mokeyish/obsidian-code-emitter/assets/15819212/58b50d86-dff7-4976-b607-16d75d1b2de8)
