### ISSUE TITLE
Manifest.json points to the wrong release version

### ISSUE THREAD

**Issue by liamcain** [mokeyish/obsidian-code-emitter#4]
Hi @mokeyish, I just wanted to see if you still wanted this plugin to be added to Obsidian's list of community plugins. There's still an outstanding issue on the pull request here: https://github.com/obsidianmd/obsidian-releases/pull/1102.

**Comment by mokeyish** [comment]
Sorry for late reply, I have add the missing release 0.0.8. please review again. Thanks!
