### ISSUE TITLE
support html, css ,please

### ISSUE THREAD

**Issue by shifenhutu** [mokeyish/obsidian-code-emitter#6]

**Comment by mokeyish** [comment]
I don't understand what effect you want.  Html/Css is not strictly a programming language.

**Comment by tsbertalan** [comment]
Probably they mean to support more than plain-text output, like how Jupyter shows [HTML reprs](https://matthewrocklin.com/blog/2019/07/04/html-repr) if available. Related to #16 and #13 , and probably others asking for image output.

**Comment by mokeyish** [comment]
https://github.com/mokeyish/obsidian-code-emitter/commit/3bd0c4d3a51b449f28e119227d24f7b4defd4f00
