### ISSUE TITLE
Request for Adding C and C++ Support

### ISSUE THREAD

**Issue by zynfly** [mokeyish/obsidian-code-emitter#8]
First of all, I would like to express my gratitude for creating such an amazing Obsidian plugin. 

I noticed that the plugin currently does not support C and C++, and I believe that adding this feature could benefit many users. I recently came across a website called [cpp.sh](https://cpp.sh/) which may be useful in adding C and C++ support, as it uses emcc and returns wasm files. However, since I am not familiar with JavaScript and TypeScript, I don't have the ability to add this feature myself. Therefore, I am writing to request if you could consider adding C and C++ support to your plugin.

I understand that you may have other priorities and limitations, so please do not feel obliged to comply with this request. However, if you are able to add support for C and C++, I believe it could help attract more users and make your plugin more diverse.

Thank you for your time and consideration.

**Comment by mokeyish** [comment]
Does [cpp.sh](https://cpp.sh/) allow CORS?

**Comment by mokeyish** [comment]
If [cpp.sh](https://cpp.sh/) allow CORS. It would be esay to support C and C++.

Just like rust

https://github.com/mokeyish/obsidian-code-emitter/blob/0148e437c5435b97c68a346eb14ac6990039030a/src/backend/languages/rust.ts#L1-L28

**Comment by zynfly** [comment]
I tested the interface using the HTTP testing tool in Clion and it looks fine.
```
### POST the code to https://cpp.sh/ajax
POST https://cpp.sh/ajax
Accept: */*
Content-Type: application/x-www-form-urlencoded

dlct=cpp20&wrng=Wall&optm=O0&source=%2F%2F%20Example%20program%0A%23include%20%3Ciostream%3E%0A%23include%20%3Cstring%3E%0A%0Aint%20main()%0A%7B%0A%20%20std%3A%3Astring%20name%3B%0A%20%20std%3A%3Acout%20%3C%3C%20%22What%20is%20your%20name%3F%20%22%3B%0A%20%20getline%20(std%3A%3Acin%2C%20name)%3B%0A%20%20std%3A%3Acout%20%3C%3C%20%22Hello%2C%20%22%20%3C%3C%20name%20%3C%3C%20%22!%5Cn%22%3B%0A%7D



### GET the worker.js
GET https://cpp.sh/v100/worker.js?388bc7b4573253416b1a1b8fb98cf455
Accept: */*

<> 2023-05-11T145928.200.js
```

**Comment by zynfly** [comment]
I don't know how to call the wasm file

**Comment by mokeyish** [comment]
This should work. Copy following to obsidian.

```markdown

```ts
const run = async (code: string, lang: 'cpp') => {
	const url = 'https://api2.sololearn.com/v2/codeplayground/v2/compile';
	const header = {
		"User-Agent": 'Obsidian Code Emitter/0.1.0',
		"Client-Agent": 'Obsidian Code Emitter/0.1.0 (If this is not allowed, please let me know)',
		"Accept": 'application/json, text/plain, */*',
		"Accept-Language": 'zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2',
		"Content-Type": 'application/json',
	};
		
	const res = await fetch(url, {
		"headers": header,
		"body": JSON.stringify({
			"code": code,
			"codeId": null,
			"input": '',
			"language": lang
		}),
		"method": 'POST',
  });
  return (await res.json()).data.output;
}

const cpp_code = `
// Example program
#include <iostream>
#include <string>

int main()
{
  std::cout << "Hello,  Obsidian Code Emitter";
}
`;

const go_code = `
package main

import "fmt"

func main() {

    fmt.Println("Happy coding!")
    
}
`;

console.log(await run(go_code, 'go'));
```

```

**Comment by mokeyish** [comment]
`cpp.sh` dose't allow CORS. you can try https://github.com/mokeyish/obsidian-code-emitter/issues/8#issuecomment-1543760367

In theory, it can support input by redirecting the input stream.  But I've been busy recently, so I don't have time to study this.

**Comment by zynfly** [comment]
Ok, I'll try it. and learn about typescript, too.

**Comment by mokeyish** [comment]
I've add C/C++ Support(via [sololearn](https://www.sololearn.com))
