### ISSUE TITLE
Request for golang support (via the go playground)

### ISSUE THREAD

**Issue by systemmonkey42** [mokeyish/obsidian-code-emitter#9]
Any change for supporting GO?

https://go.dev/play/

**Comment by mokeyish** [comment]
`go.dev` dosen't allow CORS. You can try this https://github.com/mokeyish/obsidian-code-emitter/issues/8#issuecomment-1543760367

**Comment by mokeyish** [comment]
I've add Golang Support(via [sololearn](https://www.sololearn.com))

**Comment by mokeyish** [comment]
> Any change for supporting GO?
> 
> https://go.dev/play/


It would be even better if you can let the golang official allow that website to cross-domain.
